#! /bin/bash

set -e

export SCONSFLAGS="-j8"
OPTIONS="profile=profiles/minimal.py platform=server linker=mold"

~/.local/bin/scons $OPTIONS

SRC="./bin/godot_server.x11.opt.tools.64"
DST="$HOME/bin/godot-export"

[[ "$DEBUG" == "1" ]] && exit 0

if ! cmp --quiet "$SRC" "$DST"; then
    cp "$SRC" "$DST"
    strip "$DST"
    echo "✔ Godot Export updated"
else
    echo "Already up to date"
fi
