name: Build Godot
description: Build Godot with the provided options.
inputs:
  tests:
    description: If tests are to be built.
    default: false
  platform:
    description: The Godot platform to build.
    required: false
runs:
  using: "composite"
  steps:
    - name: Scons Build
      shell: sh
      env:
          SCONS_CACHE: "${{ github.workspace }}/.scons-cache/"
          SCONS_CACHE_LIMIT: 7168
      run: |
        echo "Building with flags:" ${{ env.SCONSFLAGS }}
        echo "Environment"; env
        scons platform=${{ inputs.platform }} tools=no target=release --jobs=2 ${{ env.SCONSFLAGS }}
        ls -l bin/
