name: 🔗 GHA
on:
  push:
    branches:
      - 3.x-custom
      - 3.x-custom-build

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  static-checks:
    name: 📊 Static
    uses: ./.github/workflows/static_checks.yml

  custom-build:
    name: Custom Godot build
    needs: static-checks
    uses: ./.github/workflows/custom_build.yml
    secrets: inherit
